<form class="form-horizontal col-md-6 col-md-offset-3" action="/edit/<?= $book->id?>" method="POST">
	<div class="form-group">
		<label for="name" class="col-sm-2 control-label">Name</label>
		<div class="col-sm-10">
			<input type="text" name="name" class="form-control" id="name" placeholder="Name" value="<?= $book->name?>" />
		</div>
	</div>
	<div class="form-group">
		<label for="position" class="col-sm-2 control-label">Position</label>
		<div class="col-sm-10">
			<input type="text" name="position" class="form-control" id="position" placeholder="Position" value="<?= $book->position?>" />
		</div>
	</div>
	<div class="form-group">
		<label for="description" class="col-sm-2 control-label">Description</label>
		<div class="col-sm-10">
			<textarea class="form-control" rows="3" name="description" placeholder="Description"><?= $book->description ?></textarea>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" name="submit" value="submit" class="btn btn-success">Update</button>
		</div>
	</div>
</form>