<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title><?= $title ?: 'Web应用' ?></title>
<meta http-equiv="Content-Style-Type" content="text/css" />
<meta http-equiv="Content-Script-Type" content="text/javascript" />
<base href="<?php echo BASE_URL ?>" />
<link rel="stylesheet" href="public/css/bootstrap.css" type="text/css" />
<script src="public/js/jquery.js" type="text/javascript"></script>
<script src="public/js/bootstrap.js" type="text/javascript"></script>
<style>
	body {
		font-family: "Lantinghei SC","Microsoft Yahei","Hiragino Sans GB","Helvetica Neue",Helvetica,Arial,sans-serif;
	}
</style>
</head>
<body class="container" style="padding-top: 10px;">
	<div class="jumbotron">
		<h3 style="text-align: center;"><?= $title ?></h3>
	</div>
	<?= $body ?>
</body>
</html>